# Generated by Django 4.2.10 on 2025-04-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_genre', models.CharField(max_length=100)),
                ('visual_atmosphere', models.CharField(max_length=100)),
                ('thematic_keywords', models.CharField(max_length=200)),
                ('cultural_references', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', max_length=50)),
                ('universe_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('story_act_1', models.TextField()),
                ('story_act_2', models.TextField()),
                ('story_act_3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('significance', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='generator.gameconcept')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('narrative_role', models.CharField(max_length=200)),
                ('background', models.TextField()),
                ('gameplay_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='generator.gameconcept')),
            ],
        ),
    ]
