# Generated by Django 5.2 on 2025-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconcept',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concept/'),
        ),
    ]
