# Generated by Django 5.2 on 2025-04-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_gameconcept_language'),
        ('generator', '0003_gameconcept_user'),
    ]

    operations = [
    ]
