# Generated by Django 5.2 on 2025-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_gameconcept_image'),
        ('generator', '0004_merge_0002_gameconcept_language_0003_gameconcept_user'),
    ]

    operations = [
    ]
